[book]
authors = ["Frequency"]
language = "en"
multilingual = false
src = "pages"
title = "Frequency Documentation"

[preprocessor.local]
command = "node preprocessor.mjs"

[output.html]
no-section-label = true
copy-fonts = false # Switched to custom fonts
site-url = "/pages/"
git-repository-url = "https://github.com/frequency-chain/docs"
edit-url-template = "https://github.com/frequency-chain/docs/blob/main/{path}"
preferred-dark-theme = "coal"
additional-css = [
  "css/side-nav.css",
  "css/extended.css",
  "css/highlight.css",
  "css/highlight-dark.css",
]

# https://github.com/Michael-F-Bryan/mdbook-linkcheck
[output.linkcheck]
exclude = [
  'github\.com/paseo-network',
  'github\.com/frequency-chain/docs',
  'github\.com/frequency-chain/frequency/releases',
  'github\.com/frequency-chain/frequency',
  'twitter\.com',
  'www\.frequency\.xyz',
]
follow-web-links = true
traverse-parent-directories = false

[output.html.fold]
enable = true
