[book]
authors = ["Frequency"]
language = "en"
src = "pages"
title = "Frequency Documentation"

[preprocessor.button-links]
command = "node preprocessors/button-links.mjs"

[preprocessor.svg-embed]
command = "node preprocessors/svg-embed.mjs"

[preprocessor.title-image]
command = "node preprocessors/title-image.mjs"

[preprocessor.tailwind]
renderers = ["html"]
command = 'node preprocessors/noop-npx.mjs "npx -y @tailwindcss/cli -i ./theme/css/tailwind.css -o ./css/tailwind.css"'

[output.html]
no-section-label = true
copy-fonts = false # Switched to custom fonts
site-url = "/"
git-repository-url = "https://github.com/frequency-chain/docs"
edit-url-template = "https://github.com/frequency-chain/docs/blob/main/{path}"
preferred-dark-theme = "coal"
additional-css = [
  "css/tailwind.css",
  "css/overrides.css",
  "css/side-nav.css",
  "css/button-links.css",
  "css/highlight.css",
  "css/highlight-dark.css",
]

[output.html.redirect]
"/Core.html" = "/Whitepaper.html"

[output.html.fold]
enable = true
